### ISSUE TITLE
The export of smartAccount values is missing in the useETHProvider method.

### ISSUE THREAD

**Issue by AutumnFrosti** [Particle-Network/particle-btc-connect#8]
According to the documentation, the values of evmAccount and smartAccount can be exported using the following approach: const { evmAccount, smartAccount } = useETHProvider();. However, in reality, I found that it's impossible to export the value of smartAccount. Upon inspection, I discovered that smartAccount does not exist within useETHProvider.

`
(alias) useETHProvider(): {
    provider: EthereumProvider;
    evmAccount: string | undefined;
    switchChain: (chainId: number) => Promise<void>;
    chainId: number | undefined;
    getFeeQuotes: (tx: Transaction | Transaction[]) => Promise<...>;
    buildUserOp: ({ tx, feeQuote, tokenPaymasterAddress }: UserOpParams) => Promise<...>;
    sendUserOp: (params: SendTransactionParams, forceHideConfirmModal?: boolean | undefined) => Promise<...>;
    publicClient: {
        ...;
    } | undefined;
}
import useETHProvider
`

Library version: "@particle-network/btc-connectkit": "1.0.0-alpha.12",

**Comment by chaichuanfa** [comment]
The latest version remove `smartAccount` from `useETHProvider()`, please check the docs: https://developers.particle.network/reference/btc-connect-web
